//    HipparchiaGoBuilder
//    Copyright: E Gunderson 2025-26
//    License: GNU GENERAL PUBLIC LICENSE 3
//        (see LICENSE in the top level directory of the distribution)

package worklines3cleanup

import "strings"

// left column generated via HGS Buildwklocationmap():
// 	lk := gen.StringMapKeysIntoSlice(locations)
//	sort.Strings(lk)
//	for _, l := range lk {
//		fmt.Println(l)
//	}

var (
	provremapper = map[string]string{
		"@Yıldız":                         "@Yıldız",
		"Abritus (Hisarlâka)":             "Abritus (Hisarlâka)",
		"Abydos":                          "Abydos",
		"Abydos; Hieron":                  "Abydos; Hieron",
		"Abys.":                           "Abys.",
		"Abyssinia":                       "Abyssinia",
		"Acarnania":                       "Acarnania",
		"Ach.":                            "Achaia",
		"Achaia":                          "Achaia",
		"Achaia Phthiotis":                "Achaia Phthiotis",
		"Achilles-Tepe":                   "Achilles-Tepe",
		"Adalı":                           "Adalı",
		"Adana Mus.":                      "Adana Mus.",
		"Adatepe":                         "Adatepe",
		"Adatepe (Ort)":                   "Adatepe (Ort)",
		"Adramytteion I (Ören)":           "Adramytteion I (Ören)",
		"Adramytteion II":                 "Adramytteion II",
		"Adramytteion II (Edremit)":       "Adramytteion II",
		"Aeg. Isl.":                       "Aegean Islands",
		"Aeg.Isl.":                        "Aegean Islands",
		"Aeg.Isl.／Att.":                   "Aegean Islands／Attica",
		"Aegean Isl.":                     "Aegean Isl.",
		"Aegean Islands":                  "Aegean Islands",
		"Aegyptos":                        "Egypt",
		"Aegyptus":                        "Egypt",
		"Aemilia":                         "Aemilia",
		"Aetolia":                         "Aetolia",
		"Africa Proconsularis":            "Africa Proconsularis",
		"Ag. Apostoloi bei Muklia":        "Ag. Apostoloi bei Muklia",
		"Agathopolis (Ahtopol)":           "Agathopolis (Ahtopol)",
		"Ağanın Bağbaşı":               "Ağanın Bağbaşı",
		"Ahlatbayırı":                     "Ahlatbayırı",
		"Aig.":                            "Aigina",
		"Aigina":                          "Aigina",
		"Ainis":                           "Ainis",
		"Aiolien":                         "Aiolien",
		"Aitolia":                         "Aitolia",
		"Akalan／Orhaneli":                 "Akalan／Orhaneli",
		"Akarnania":                       "Akarnania",
		"Akçaavlu":                       "Akçaavlu",
		"Akçalar":                        "Akçalar",
		"Akçapınar":                      "Akçapınar",
		"Akköy":                           "Akköy",
		"Akrai":                           "Akrai",
		"Aksakal":                         "Aksakal",
		"Aksakal ／ Erdek-Kyzikos":         "Aksakal ／ Erdek-Kyzikos",
		"Akşakal":                        "Akşakal",
		"Alacaoluk":                       "Alacaoluk",
		"Albania":                         "Albania",
		"Alexandreia Troas":               "Alexandria",
		"Alexandria":                      "Alexandria",
		"Alexandria Mus.":                 "Alexandria",
		"Alexandria Troas":                "Alexandria",
		"Alexandria Troas (Dalyan)":       "Alexandria",
		"Alexandria Troas (Eskistambul)":  "Alexandria",
		"Alexandria Troas (bei Eskistamb": "Alexandria",
		"Ali Hocalar":                     "Ali Hocalar",
		"Alibey Köy":                      "Alibey Köy",
		"Alpağut":                        "Alpağut",
		"Amorgos":                         "Amorgos",
		"Anaphe":                          "Anaphe",
		"Anchialus (Pomorie)":             "Anchialus (Pomorie)",
		"Andros":                          "Andros",
		"Anhöhe bei Zeytinli":             "Anhöhe bei Zeytinli",
		"Antandros":                       "Antandros",
		"Apameia (Dinar)":                 "Apameia (Dinar)",
		"Apollonia (Sozopol)":             "Apollonia (Sozopol)",
		"Apollonia (Uluborlu)":            "Apollonia (Uluborlu)",
		"Apollonia ad Rhynd. (Gölyaz—":    "Apollonia ad Rhynd. (Gölyaz—",
		"Apulia":                          "Apulia",
		"Aquileia":                        "Aquileia",
		"Arabli-Çesme":                   "Arabli-Çesme",
		"Arg.":                            "Arg.",
		"Argeia":                          "Argeia",
		"Argia":                           "Argia",
		"Argiza (Pazarköy)":               "Argiza (Pazarköy)",
		"Argolis":                         "Argolis",
		"Argos":                           "Argos",
		"Aristaeum (Emona)":               "Aristaeum (Emona)",
		"Arizköy":                         "Arizköy",
		"Ark.":                            "Arkadia",
		"Arkadia":                         "Arkadia",
		"Arkesine":                        "Arkesine",
		"Artake":                          "Artake",
		"Artake (Erdek)":                  "Artake (Erdek)",
		"Artemis Thermaia (Gönen)":        "Artemis Thermaia (Gönen)",
		"Arıklar":                         "Arıklar",
		"Arızköy":                         "Arızköy",
		"Asamus River":                    "Asamus River",
		"Asar Kale":                       "Asar Kale",
		"Asar nahe Alpağut":              "Asar nahe Alpağut",
		"Asirlik":                         "Asirlik",
		"Asklepieion":                     "Asklepieion",
		"Assarköy":                        "Assarköy",
		"Assartepe":                       "Assartepe",
		"Assos":                           "Assos",
		"Assos (Behramkale)":              "Assos (Behramkale)",
		"Astypalaea":                      "Astypalaea",
		"Astypalaia":                      "Astypalaia",
		"Astyra (Ilıca)":                  "Astyra (Ilıca)",
		"Aşağı Acaalan":                 "Aşağı Acaalan",
		"Aşağı Kırıkla":                 "Aşağı Kırıkla",
		"Aşağıyapıcı":                   "Aşağıyapıcı",
		"Ath.":                            "Athens",
		"Athens":                          "Athens",
		"Athribis":                        "Athribis",
		"Att.":                            "Attica",
		"Att.／Delos":                      "Attica／Delos",
		"Attic":                           "Attica",
		"Attica":                          "Attica",
		"Attika":                          "Attica",
		"Attike":                          "Attica",
		"Augusta Traiana (Stara Zagora)":  "Augusta Traiana (Stara Zagora)",
		"Aulonia (Hamdibey)":              "Aulonia (Hamdibey)",
		"Aureliane (Havran)":              "Aureliane (Havran)",
		"Avcılar":                         "Avcılar",
		"Ayvalıdere":                      "Ayvalıdere",
		"Azmak Ada":                       "Azmak Ada",
		"Bakırköy":                        "Bakırköy",
		"Ballıpinarı":                     "Ballıpınarı",
		"Ballıpınarı":                     "Ballıpınarı",
		"Balıkesir":                       "Balıkesir",
		"Balıklı":                         "Balıklı",
		"Bandirma":                        "Bandirma",
		"Bandirma ／ Erdek ／ Aksakal":      "Bandirma ／ Erdek ／ Aksakal",
		"Bandırma":                        "Bandırma",
		"Baraklı":                         "Baraklı",
		"Basak":                           "Basak",
		"Batak Oba":                       "Batak Oba",
		"Bayat":                           "Bayat",
		"Bayramiç":                       "Bayramiç",
		"Bekdemir":                        "Bekdemir",
		"Bekirli":                         "Bekirli",
		"Belenören":                       "Belenören",
		"Belkız":                          "Belkız",
		"Bereketli":                       "Bereketli",
		"Bergamabağları":                 "Bergamabağları",
		"Bergaz":                          "Bergaz",
		"Bergdorf bei Soma":               "Bergdorf bei Soma",
		"Bergkuppe nahe Kestelek":         "Bergkuppe nahe Kestelek",
		"Beşik Tepe":                     "Beşik Tepe",
		"Beyel":                           "Beyel",
		"Beyköy":                          "Beyköy",
		"Bigadiç":                        "Bigadiç",
		"Biğa":                           "Biğa",
		"Bith.":                           "Bith.",
		"Bithynia":                        "Bithynia",
		"Bithynien":                       "Bithynien",
		"Biyikli Alanı":                   "Biyikli Alanı",
		"Bizone (Kavarna)":                "Bizone (Kavarna)",
		"Boğazköy":                       "Boğazköy",
		"Boi.":                            "Boi.",
		"Boiotia":                         "Boiotia",
		"Boyalıca":                        "Boyalıca",
		"Bozen":                           "Bozen",
		"Brittania":                       "Brittania",
		"Bruttii":                         "Bruttii",
		"Brücke Boghaz über den Kaikos":   "Brücke Boghaz über den Kaikos",
		"Brücke Guzel-Kupru":              "Brücke Guzel-Kupru",
		"Bükköy":                          "Bükköy",
		"Büyükbalıklı":                    "Büyükbalıklı",
		"Büyüksoğuklar":                  "Büyüksoğuklar",
		"C. Crete":                        "C. Crete",
		"Cakmak":                          "Cakmak",
		"Calabria":                        "Calabria",
		"Camandıra Çiftlik":              "Camandıra Çiftlik",
		"Campania":                        "Campania",
		"Campania et vicinia":             "Campania et vicinia",
		"Car.":                            "Car.",
		"Caron Limenos (Šabla pr.)":      "Caron Limenos (Šabla pr.)",
		"Central Aegean":                  "Central Aegean",
		"Ceos":                            "Ceos",
		"Chalke":                          "Chalke",
		"Chersonesos":                     "Chersonesos",
		"Chorsiai":                        "Chorsiai",
		"Cil.":                            "Cil.",
		"Cimolos":                         "Cimolos",
		"Cinaros":                         "Cinaros",
		"Cispadana":                       "Cispadana",
		"Cnidian peninsula":               "Cnidian peninsula",
		"Corinthia":                       "Corinth",
		"Cr.":                             "Crete",
		"Crete":                           "Crete",
		"Cythnos":                         "Cythnos",
		"Çağış":                        "Çağış",
		"Çakıl":                          "Çakıl",
		"Çakırca":                        "Çakırca",
		"Çalışkan":                      "Çalışkan",
		"Çamlıca":                        "Çamlıca",
		"Çanakkalessi":                   "Çanakkalessi",
		"Çançavuş":                     "Çançavuş",
		"Çardak":                         "Çardak",
		"Çatalağıl":                     "Çatalağıl",
		"Çatalçam":                      "Çatalçam",
		"Çavuş bei Manyas":              "Çavuş bei Manyas",
		"Çavuşköy":                      "Çavuşköy",
		"Çavuştepe ／ Çifteler":         "Çavuştepe ／ Çifteler",
		"Çayağzı":                       "Çayağzı",
		"Çelen Bağları":                 "Çelen Bağları",
		"Çepni":                          "Çepni",
		"Çiklar":                         "Çiklar",
		"Çiplak":                         "Çiplak",
		"Çiplak (a":                      "Çiplak (a",
		"Çirpılar":                       "Çirpılar",
		"Çördük":                         "Çördük",
		"Çınarlı":                        "Çınarlı",
		"Çınarpınar Kale":                "Çınarpınar Kale",
		"Çıplak":                         "Çıplak",
		"Dağdibi Köy":                    "Dağdibi Köy",
		"Dağkadı Köy":                    "Dağkadı Köy",
		"Dalmatia":                        "Dalmatia",
		"Danube ﹠ Haemus Rivers":          "Danube ﹠ Haemus Rivers",
		"Danışment":                      "Danışment",
		"Dardanellen":                     "Dardanellen",
		"Dardanos":                        "Dardanos",
		"Dardanos (Mal-Tepe)":             "Dardanos (Mal-Tepe)",
		"Darıca":                          "Darıca",
		"Darıköy":                         "Darıköy",
		"Daskyleion (Ergili)":             "Daskyleion (Ergili)",
		"Dedepınarköy bei Bandı":          "Dedepınarköy bei Bandı",
		"Değirmencik":                    "Değirmencik",
		"Delos":                           "Delos",
		"Delphi":                          "Delphi",
		"Demetrias":                       "Demetrias",
		"Demir Boku":                      "Demir Boku",
		"Demirci (﹦Demircidere)":          "Demirci (﹦Demircidere)",
		"Demirciler":                      "Demirciler",
		"Demirkapı":                       "Demirkapı",
		"Derekadı Köy":                    "Derekadı Köy",
		"Dereköy":                         "Dereköy",
		"Dereli":                          "Dereli",
		"Deultum (Debelt)":                "Deultum (Debelt)",
		"Devecikonağı":                   "Devecikonağı",
		"Dikili-Bayır":                    "Dikili-Bayır",
		"Dionysopolis (Balčik)":          "Dionysopolis (Balčik)",
		"Discoduraterae (Gostlica)":       "Discoduraterae (Gostlica)",
		"Doğancılar":                     "Doğancılar",
		"Doğanpınar":                     "Doğanpınar",
		"Doğruca":                        "Doğruca",
		"Doliche":                         "Doliche",
		"Dorf südlich von Mustafakemalp":  "Dorf südlich von Mustafakemalp",
		"Doris":                           "Doris",
		"Driskoli":                        "Driskoli",
		"Durostorum (Silistra)":           "Durostorum (Silistra)",
		"Dutlimanı":                       "Dutlimanı",
		"Dümrek":                          "Dümrek",
		"E. Aegean":                       "Aegean",
		"E. Argolid":                      "Argolid",
		"E. Crete":                        "Crete",
		"Eastern Aegean":                  "Aegean",
		"Edessa":                          "Edessa",
		"Edincik":                         "Edincik",
		"Eg.":                             "Egypt",
		"Egypt":                           "Egypt",
		"El.":                             "El.",
		"Elaia":                           "Elaia",
		"Elephantine Isl.":                "Elephantine Isl.",
		"Eleusis":                         "Eleusis",
		"Elis":                            "Elis",
		"Emreköy":                         "Emreköy",
		"Ephesos":                         "Ephesos",
		"Epid.":                           "Epidauros",
		"Epidauria":                       "Epidauros",
		"Epidauros":                       "Epidauros",
		"Epiros":                          "Epiros",
		"Erdek Museum":                    "Erdek Museum",
		"Eretria":                         "Eretria",
		"Erite (Dolni Bliznak)":           "Erite (Dolni Bliznak)",
		"Eski Köy (am Sızak Deresi":       "Eski Köy (am Sızak Deresi",
		"Eski Köy yeri":                   "Eski Köy yeri",
		"Eski Manyas (Poimanenon)":        "Eski Manyas (Poimanenon)",
		"Eskiçatal":                      "Eskiçatal",
		"Eskıbalcik":                      "Eskıbalcik",
		"Etruria":                         "Etruria",
		"Euboia":                          "Euboia",
		"Euboien":                         "Euboien",
		"Ezine":                           "Ezine",
		"Fadılköy":                        "Fadılköy",
		"Feld Cakıl arası Mevkii":         "Feld Cakıl arası Mevkii",
		"Felsgrab bei Turnacık":           "Felsgrab bei Turnacık",
		"Festland gegenüber Azmak Ada":    "Festland gegenüber Azmak Ada",
		"Flur Caltılık Mevkii be":         "Flur Caltılık Mevkii be",
		"Flur Maşatlık bei Resull":       "Flur Maşatlık bei Resull",
		"Flur Ören Arasi bei Boyalı":      "Flur Ören Arasi bei Boyalı",
		"Flur Ören Mevkii bei Sarıs":      "Flur Ören Mevkii bei Sarıs",
		"Frentani":                        "Frentani",
		"Friedhof bei Bergama (2247)":     "Friedhof bei Bergama (2247)",
		"Friedhof bei Bergama (2248)":     "Friedhof bei Bergama (2248)",
		"Friedhof bei Reşadiye Iskele":   "Friedhof bei Reşadiye Iskele",
		"Friedhof südöstl. von Cıp":       "Friedhof südöstl. von Cıp",
		"Fıranlı":                         "Fıranlı",
		"Gal.":                            "Gal.",
		"Gal. Phryg.":                     "Gal. Phryg.",
		"Galat.":                          "Galat.",
		"Gallia":                          "Gallia",
		"Gallia Belgica":                  "Gallia",
		"Gallia Norben":                   "Gallia",
		"Gargara (Nusratlı-Burun)":        "Gargara (Nusratlı-Burun)",
		"Gaulos":                          "Gaulos",
		"Gegend von Ergili_Manyas-See":    "Gegend von Ergili_Manyas-See",
		"Gegend von Troja":                "Gegend von Troja",
		"Gergis (bei Karıncalı)":          "Gergis (bei Karıncalı)",
		"Germania":                        "Germania",
		"Germania Inferior":               "Germania",
		"Germe (Soma)":                    "Germe (Soma)",
		"Geyikli":                         "Geyikli",
		"Gorna Gradešnica_Ilindenci":     "Gorna Gradešnica_Ilindenci",
		"Gortyna":                         "Gortyna",
		"Graecia":                         "Graecia",
		"Gyaros":                          "Gyaros",
		"Göbel":                           "Göbel",
		"Gölyazı":                         "Gölyazı",
		"Gönüköy":                         "Gönüköy",
		"Gümüşçay":                      "Gümüşçay",
		"Gümüşpınarı":                    "Gümüşpınarı",
		"Günaydın":                        "Günaydın",
		"Gündoğdu":                       "Gündoğdu",
		"Güreci":                          "Güreci",
		"Hadrianeia":                      "Hadrianeia",
		"Hadrianeia (Dursunbey)":          "Hadrianeia (Dursunbey)",
		"Hadrianoi pros Olympon":          "Hadrianoi pros Olympon",
		"Hadrianoi pros Olympon (Orhanel": "Hadrianoi pros Olympon (Orhanel",
		"Hadrianopolis (Edirne)":          "Hadrianopolis (Edirne)",
		"Hadrianotherai":                  "Hadrianotherai",
		"Hafızhüseyinbey":                 "Hafızhüseyinbey",
		"Halileli":                        "Halileli",
		"Halkapınar":                      "Halkapınar",
		"Halonnesus":                      "Halonnesus",
		"Hamamlı":                         "Hamamlı",
		"Hasanağa":                       "Hasanağa",
		"Hatipler":                        "Hatipler",
		"Haydar":                          "Haydar",
		"Hecatonnesi":                     "Hecatonnesi",
		"Heraclea":                        "Heraclea",
		"Herm.":                           "Herm.",
		"Hermionis":                       "Hermionis",
		"Hestiaiotis":                     "Hestiaiotis",
		"Hierapytna":                      "Hierapytna",
		"Hisar":                           "Hisar",
		"Hisarlık-Tepe (a":                "Hisarlık-Tepe (a",
		"Hispania":                        "Hispania",
		"Hissaralan":                      "Hissaralan",
		"Histria":                         "Histria",
		"Histria (Istros)":                "Histria (Istros)",
		"Hobandanışment":                 "Hobandanışment",
		"Hyettos":                         "Hyettos",
		"Hügel oberhalb Akçapına":        "Hügel oberhalb Akçapına",
		"Ikos":                            "Ikos",
		"Ilhan":                           "Ilhan",
		"Ilion (Hisarlık-Tepe)":           "Ilion (Hisarlık-Tepe)",
		"Ilion (Hısarlık-Tepe)":           "Ilion (Hısarlık-Tepe)",
		"Ilyaslar":                        "Ilyaslar",
		"Imbros":                          "Imbros",
		"Inci Baba Teke":                  "Inci Baba Teke",
		"Insel Thasos() (Mutlu Adas𐅽":     "Insel Thasos() (Mutlu Adas𐅽",
		"Intepe":                          "Intepe",
		"Ion.":                            "Ionia",
		"Ionia":                           "Ionia",
		"Ionian Isl.":                     "Ionian Islands",
		"Ionian Islands":                  "Ionian Islands",
		"Ionien":                          "Ionia",
		"Ios":                             "Ios",
		"Ioulia Gordos (Gördes)":          "Ioulia Gordos (Gördes)",
		"Iskele von Tavaklı":              "Iskele von Tavaklı",
		"Issızhan":                        "Issızhan",
		"Istros":                          "Istros",
		"It.":                             "Italia",
		"Ital.":                           "Italia",
		"Italia":                          "Italia",
		"Italien":                         "Italien",
		"Iulis":                           "Iulis",
		"Kabakum":                         "Kabakum",
		"Kabulbaba Köy":                   "Kabulbaba Köy",
		"Kadyanda":                        "Kadyanda",
		"Kadı Köy":                        "Kadı Köy",
		"Kaikos-Kanalleitung":             "Kaikos-Kanalleitung",
		"Kalafat":                         "Kalafat",
		"Kalarga":                         "Kalarga",
		"Kalymna":                         "Kalymna",
		"Kangırlı":                        "Kangırlı",
		"Kapaklı Kale":                    "Kapaklı Kale",
		"Kapelle Ag. Georgios (1902)":     "Kapelle Ag. Georgios (1902)",
		"Kapelle des Ioannis":             "Kapelle des Ioannis",
		"Kapelle ssö. von  Evciler":       "Kapelle ssö. von  Evciler",
		"Kapıağzı":                       "Kapıağzı",
		"Kapıkaya":                        "Kapıkaya",
		"Kara Yakuplu":                    "Kara Yakuplu",
		"Karaağac":                       "Karaağac",
		"Karabağ Çiftlik":               "Karabağ Çiftlik",
		"Karabunar":                       "Karabunar",
		"Karacabey":                       "Karacabey",
		"Karacabey Harası":                "Karacabey Harası",
		"Karacabey Kazanlarköy":           "Karacabey Kazanlarköy",
		"Karacabey od. Umgebung":          "Karacabey od. Umgebung",
		"Karacabey oder Umgebung":         "Karacabey oder Umgebung",
		"Karacabey ／ Ergili od. Kyziko":   "Karacabey ／ Ergili od. Kyziko",
		"Karacabey ／ Gönen":               "Karacabey ／ Gönen",
		"Karacabey ／ Iznik":               "Karacabey ／ Iznik",
		"Karacabey ／ Mustafakemalpas﹡":    "Karacabey ／ Mustafakemalpas﹡",
		"Karacagaç":                      "Karacagaç",
		"Karacaören":                      "Karacaören",
		"Karaçaltı":                      "Karaçaltı",
		"Karaköy Ören Harabesi":           "Karaköy Ören Harabesi",
		"Karia":                           "Caria",
		"Karien":                          "Caria",
		"Karpathos":                       "Karpathos",
		"Karşıyaka":                      "Karşıyaka",
		"Kasos":                           "Kasos",
		"Kastell bei Ovabayındır":         "Kastell bei Ovabayındır",
		"Kavaklı":                         "Kavaklı",
		"Kayabaşı":                       "Kayabaşı",
		"Kayatepe Köy":                    "Kayatepe Köy",
		"Kayırlar":                        "Kayırlar",
		"Kebren (Fuğla(n) Tepe)":         "Kebren (Fuğla(n) Tepe)",
		"Kebren (Fuğla(n)-Tepe)":         "Kebren (Fuğla(n)-Tepe)",
		"Keles":                           "Keles",
		"Keles oder Umgebung":             "Keles oder Umgebung",
		"Kemaliye":                        "Kemaliye",
		"Kemalli":                         "Kemalli",
		"Kephisia":                        "Kephisia",
		"Kepsut":                          "Kepsut",
		"Kestambol":                       "Kestambol",
		"Kestelek":                        "Kestelek",
		"Keşlik":                         "Keşlik",
		"KiliKia":                         "Cilicia",
		"Kilikia":                         "Cilicia",
		"Kilikien":                        "Cilicia",
		"Kilise Tepe":                     "Kilise Tepe",
		"Kirazlı":                         "Kirazlı",
		"Kirazpınar":                      "Kirazpınar",
		"Kiresen":                         "Kiresen",
		"Kl. Ag. Georgios am Egri-Dere":   "Kl. Ag. Georgios am Egri-Dere",
		"Kl. Ag.Eleusini":                 "Kl. Ag.Eleusini",
		"Kl. Ag.Theodorou":                "Kl. Ag.Theodorou",
		"Kl. Georgios am Kum-Liman":       "Kl. Georgios am Kum-Liman",
		"Kl. Panagia Galatiane":           "Kl. Panagia Galatiane",
		"Kle.":                            "Kle.",
		"Kleitor":                         "Kleitor",
		"Kleon.":                          "Kleon.",
		"Kleonaia":                        "Kleonaia",
		"Knosos":                          "Knosos",
		"Koca Çiftlik":                   "Koca Çiftlik",
		"Kocakoru":                        "Kocakoru",
		"Kocapınar":                       "Kocapınar",
		"Koçali":                         "Koçali",
		"Kor.":                            "Corinth",
		"Korinthia":                       "Corinth",
		"Korinthos":                       "Corinth",
		"Koryphantis (Eski Mezarlik)":     "Koryphantis (Eski Mezarlik)",
		"Kos":                             "Kos",
		"Kostak Tepe":                     "Kostak Tepe",
		"Kourion":                         "Kourion",
		"Kreta":                           "Kreta",
		"Kum Kale":                        "Kum Kale",
		"Kum Köy":                         "Kum Köy",
		"Kurfallı":                        "Kurfallı",
		"Kurfallı-Çiftlik":               "Kurfallı-Çiftlik",
		"Kurşunlu":                       "Kurşunlu",
		"Kusumlar":                        "Kusumlar",
		"Kybele auf dem Dindymon (Tsabli": "Kybele auf dem Dindymon (Tsabli",
		"Kyn.":                            "Kyn.",
		"Kynouria":                        "Kynouria",
		"Kypros":                          "Kypros",
		"Kyr.":                            "Kyr.",
		"Kyrenaike":                       "Kyrenaike",
		"Kythnos":                         "Kythnos",
		"Kyzikos":                         "Kyzikos",
		"Kyzikos (Belkız)":                "Kyzikos (Belkız)",
		"Kösedere Köy":                    "Kösedere Köy",
		"Kösehoroz Köy":                   "Kösehoroz Köy",
		"Köseler (1883)":                  "Köseler (1883)",
		"Köseresul":                       "Köseresul",
		"Köyüstü／Ahlatbayırı":             "Köyüstü／Ahlatbayırı",
		"Kücükkaraağac":                  "Kücükkaraağac",
		"Küçük Alamşah":                 "Küçük Alamşah",
		"Kıranlar":                        "Kıranlar",
		"Kıranışıklar":                   "Kıranışıklar",
		"Kızık bei Manyas":                "Kızık bei Manyas",
		"Kızılöz":                         "Kızılöz",
		"Lak.":                            "Laconia",
		"Lakonia":                         "Laconia",
		"Lakonike":                        "Laconia",
		"Lampsakos":                       "Lampsakos",
		"Lampsakos (Lapseki)":             "Lampsakos (Lapseki)",
		"Lampsakos (Lapseki) od. Umgebun": "Lampsakos (Lapseki) od. Umgebun",
		"Latium":                          "Latium",
		"Latium Adiectum":                 "Latium Adiectum",
		"Lemnos":                          "Lemnos",
		"Lemonia--Alimnia":                "Lemonia--Alimnia",
		"Leros":                           "Leros",
		"Lesbos":                          "Lesbos",
		"Leukopetra":                      "Leukopetra",
		"Liguria":                         "Liguria",
		"Lindos":                          "Lindos",
		"Locris":                          "Locris",
		"Lokris":                          "Lokris",
		"Lopadion":                        "Lopadion",
		"Lousoi":                          "Lousoi",
		"Lycia":                           "Lycia",
		"Lyd.":                            "Lydia",
		"Lydia":                           "Lydia",
		"Lydien":                          "Lydien",
		"Lyk.":                            "Lykia",
		"Lykia":                           "Lykia",
		"Lyttos":                          "Lyttos",
		"Mac.":                            "Mac.",
		"Madan Ad.":                       "Madan Ad.",
		"Madradağ-Kanalleitung":          "Madradağ-Kanalleitung",
		"Madradağ-Leitung":               "Madradağ-Leitung",
		"Madradağ-Tonrohrleitung":        "Madradağ-Tonrohrleitung",
		"Magna Graecia":                   "Magna Graecia",
		"Magnesia":                        "Magnesia",
		"Mahmun Köy":                      "Mahmun Köy",
		"Maionia (Menye)":                 "Maionia (Menye)",
		"Makedonia":                       "Makedonia",
		"Mal-Taş":                        "Mal-Taş",
		"Malis":                           "Malis",
		"Maltarlassi／Lapseki":             "Maltarlassi／Lapseki",
		"Maltepe bei Altınova":            "Maltepe bei Altınova",
		"Manyas":                          "Manyas",
		"Marcianopolis (Devnja)":          "Marcianopolis (Devnja)",
		"Megaris":                         "Megaris",
		"Megiste":                         "Megiste",
		"Melita":                          "Melita",
		"Melos":                           "Melos",
		"Menteşe":                        "Menteşe",
		"Mesambria (Nesebâr)":             "Mesambria (Nesebâr)",
		"Mess.":                           "Mess.",
		"Messenia":                        "Messenia",
		"Meter Aspondene (Nemrud Kale)":   "Meter Aspondene (Nemrud Kale)",
		"Meth.":                           "Meth.",
		"Methymna":                        "Methymna",
		"Mezarlık am Monastır De":         "Mezarlık am Monastır De",
		"Miletupolis() (Melde)":           "Miletupolis() (Melde)",
		"Misakça":                        "Misakça",
		"Moesia":                          "Moesia",
		"Moesien":                         "Moesien",
		"Mouch":                           "Mouch",
		"Mun. Montanens. (Mihailovgrad)":  "Mun. Montanens. (Mihailovgrad)",
		"Musahoca":                        "Musahoca",
		"Mustafa Kemalpaşa":              "Mustafa Kemalpaşa",
		"Mustafakemalpaşa":               "Mustafakemalpaşa",
		"Mys.":                            "Mysia",
		"Mysia":                           "Mysia",
		"Mytilene":                        "Mytilene",
		"N. Aegean Islands":               "Aegean Islands",
		"N. Black Sea":                    "Black Sea",
		"N.Black Sea":                     "Black Sea",
		"N.Gr.":                           "N.Gr.",
		"Nacak Çesme":                    "Nacak Çesme",
		"Nalbant":                         "Nalbant",
		"Nalınlar":                        "Nalınlar",
		"Nasos／Poroselene (Alibey Ad.)":   "Nasos／Poroselene (Alibey Ad.)",
		"Naulochus (Obzor)":               "Naulochus (Obzor)",
		"Naxos":                           "Naxos",
		"Neandria (Çığrı-D":             "Neandria (Çığrı-D",
		"Neapolis":                        "Neapolis",
		"Nekropole an der Strasse Mustaf": "Nekropole an der Strasse Mustaf",
		"Nesos":                           "Nesos",
		"Nicopol. ﹠ Marcianopol.":         "Nicopol. ﹠ Marcianopol.",
		"Nicopolis ad Istrum (Nikjup)":    "Nicopolis ad Istrum (Nikjup)",
		"Nicopolis ad Nestum (Gârmen)":    "Nicopolis ad Nestum (Gârmen)",
		"Nicuria":                         "Nicuria",
		"Nikomedeia":                      "Nikomedeia",
		"Nisyros":                         "Nisyros",
		"Northern Aegean":                 "Northern Aegean",
		"Novae (Stâklen)":                 "Novae (Stâklen)",
		"Nub.":                            "Nub.",
		"Oasis Major (El Khârga)":         "Oasis Major (El Khârga)",
		"Odessus (Varna)":                 "Odessus (Varna)",
		"Oescus ﹠ Utus Rivers":            "Oescus ﹠ Utus Rivers",
		"Oitaia":                          "Oitaia",
		"Oliaros":                         "Oliaros",
		"Olympia":                         "Olympia",
		"Olympos":                         "Olympia",
		"Orchomenos":                      "Orchomenos",
		"Ormanlı":                         "Ormanlı",
		"Oropia":                          "Oropia",
		"Oropos":                          "Oropos",
		"Ovabayındır":                     "Ovabayındır",
		"Paeligni":                        "Paeligni",
		"Palata Çeşmesi nördl. Ar":      "Palata Çeşmesi nördl. Ar",
		"Pamph.":                          "Pamph.",
		"Pamphyl.":                        "Pamphyl.",
		"Pamukcu":                         "Pamukcu",
		"Pannonia Inferior":               "Pannonia Inferior",
		"Pannonia Superior":               "Pannonia Superior",
		"Panormos":                        "Panormos",
		"Pantikapaion":                    "Pantikapaion",
		"Parion":                          "Parion",
		"Parion (Kemer)":                  "Parion (Kemer)",
		"Paros":                           "Paros",
		"Patara":                          "Patara",
		"Pathyris (Gebelein)":             "Pathyris (Gebelein)",
		"Pautalia (Kjustendil)":           "Pautalia (Kjustendil)",
		"Peek":                            "Peek",
		"Pel.":                            "Pel.",
		"Pelasgiotis":                     "Pelasgiotis",
		"Pelasgiotos":                     "Pelasgiotos",
		"Peparethos":                      "Peparethos",
		"Perdikiai":                       "Perdikiai",
		"Pergamon":                        "Pergamon",
		"Pericharaxis (Balya)":            "Pericharaxis (Balya)",
		"Perkote (Bergaz)":                "Perkote (Bergaz)",
		"Perrhaibia":                      "Perrhaibia",
		"Pestimalci-Çiftlik":             "Pestimalci-Çiftlik",
		"Phacussae":                       "Phacussae",
		"Philippopolis (Plovdiv)":         "Philippopolis (Plovdiv)",
		"Phl.":                            "Phl.",
		"Phliasia":                        "Phliasia",
		"Phocis":                          "Phocis",
		"Phoen.":                          "Phoen.",
		"Phoibe (Yer Ada)":                "Phoibe (Yer Ada)",
		"Phok.":                           "Phok.",
		"Phokien":                         "Phokien",
		"Phokis":                          "Phokis",
		"Pholegandros":                    "Pholegandros",
		"Phryg.":                          "Phryg.",
		"Phrygia":                         "Phrygia",
		"Phrygien":                        "Phrygien",
		"Picenum":                         "Picenum",
		"Pinara":                          "Pinara",
		"Piribeyli":                       "Piribeyli",
		"Pis.":                            "Pis.",
		"Pisidia":                         "Pisidia",
		"Pitane":                          "Pitane",
		"Pitane (Çandarli)":              "Pitane (Çandarli)",
		"Pitane (Çandarlı)":              "Pitane (Çandarlı)",
		"Piyan Mezarlık bei Çipl":        "Piyan Mezarlık bei Çipl",
		"Piyan Mezarlık bei Çipla":       "Piyan Mezarlık bei Çipla",
		"Piyan Mezarlık von Ç𐅽":          "Piyan Mezarlık von Ç𐅽",
		"Poimanenon":                      "Poimanenon",
		"Pomak Köy":                       "Pomak Köy",
		"Pont.":                           "Pont.",
		"Pont.／Gal.":                      "Pont.／Gal.",
		"Pontos":                          "Pontos",
		"Porta am Armutçuk Dağ":         "Porta am Armutçuk Dağ",
		"Priapos (Karabiga)":              "Priapos (Karabiga)",
		"Profitis Ilias／Taşlı T":         "Profitis Ilias／Taşlı T",
		"Prokonnesos":                     "Prokonnesos",
		"Pselkis (El Dakka)":              "Pselkis (El Dakka)",
		"Ptolemaïs Hermiou":               "Ptolemaïs Hermiou",
		"Recep":                           "Recep",
		"Region von Daskyleion (Ergili)":  "Region von Daskyleion (Ergili)",
		"Rhamnous":                        "Rhamnous",
		"Rhodes":                          "Rhodes",
		"Rhodian Peraia":                  "Rhodian Peraia",
		"Rhodiapolis":                     "Rhodiapolis",
		"Rhodos":                          "Rhodes",
		"Roma":                            "Roma",
		"Roma et vic":                     "Roma et vic",
		"Roma et vic.":                    "Roma et vic.",
		"Roma et vicinia":                 "Roma et vicinia",
		"S. Aegean":                       "S. Aegean",
		"Sabini":                          "Sabini",
		"Saçaklı":                        "Saçaklı",
		"Sağılar":                        "Sağılar",
		"Salamis":                         "Salamis",
		"Salurköy":                        "Salurköy",
		"Samothrace":                      "Samothrace",
		"Sandanski":                       "Sandanski",
		"Sar.Glf.":                        "Sar.Glf.",
		"Sardinia":                        "Sardinia",
		"Sarniç":                         "Sarniç",
		"Saronic Gulf":                    "Saronic Gulf",
		"Saros":                           "Saros",
		"Sarıbeyler":                      "Sarıbeyler",
		"Sarıdüzü":                        "Sarıdüzü",
		"Savaştepe":                      "Savaştepe",
		"Sazlı Dere Köy":                  "Sazlı Dere Köy",
		"Saïs (Sâ el-Hagar)":              "Saïs (Sâ el-Hagar)",
		"Scythia Minor":                   "Scythia Minor",
		"Seleukeia":                       "Seleukeia",
		"Selinus":                         "Selinus",
		"Selinus-(Osthang-)Leitung (A)":   "Selinus-(Osthang-)Leitung (A)",
		"Selinus-(Osthang-)Leitung (B)":   "Selinus-(Osthang-)Leitung (B)",
		"Selinus-(Westhang-)Leitung (C)":  "Selinus-(Westhang-)Leitung (C)",
		"Selinus-(Westhang-)Leitung (E)":  "Selinus-(Westhang-)Leitung (E)",
		"Selinus-Tal (Bergama Dere)":      "Selinus-Tal (Bergama Dere)",
		"Serceler":                        "Serceler",
		"Serceler ／ Orhaneli":             "Serceler ／ Orhaneli",
		"Serçeler":                       "Serçeler",
		"Serdica (Sofia)":                 "Serdica (Sofia)",
		"Seriphos":                        "Seriphos",
		"Seutlussa (Seskli)":              "Seutlussa (Seskli)",
		"Sevketiye":                       "Sevketiye",
		"Seyitgazi Tepesi bei Artake (Er": "Seyitgazi Tepesi bei Artake (Er",
		"Side (Eski Adalia_Selimiye)":     "Side (Eski Adalia_Selimiye)",
		"Sigeion":                         "Sigeion",
		"Sik.":                            "Sik.",
		"Sikelia":                         "Sikelia",
		"Sikilia":                         "Sikilia",
		"Sikinos":                         "Sikinos",
		"Sikyonia":                        "Sikyonia",
		"Sindel":                          "Sindel",
		"Siphnos":                         "Siphnos",
		"Siril":                           "Siril",
		"Sirinçavuş":                    "Sirinçavuş",
		"Skamandros (Akköy Yakası)":       "Skamandros (Akköy Yakası)",
		"Skamandros II":                   "Skamandros II",
		"Skepsis (Kurşulu-Tepe)":         "Skepsis (Kurşulu-Tepe)",
		"Skepsis (Kurşunlu Tepe)":        "Skepsis (Kurşunlu Tepe)",
		"Skepsis (Kurşunlu-Tepe)":        "Skepsis (Kurşunlu-Tepe)",
		"Skiathos":                        "Skiathos",
		"Skyros":                          "Skyros",
		"Skyth.min.":                      "Skyth.min.",
		"Skythia":                         "Skythia",
		"Smintheion bei Chryse (bei Gulp": "Smintheion bei Chryse (bei Gulp",
		"Smintheion bei Chryse (bei Gül":  "Smintheion bei Chryse (bei Gül",
		"Southern Aegean":                 "Southern Aegean",
		"Sparta":                          "Sparta",
		"Stengelköy":                      "Stengelköy",
		"Strymon R. Valley":               "Strymon R. Valley",
		"Sucaklı":                         "Sucaklı",
		"Sultaniye Köy":                   "Sultaniye Köy",
		"Susurluk":                        "Susurluk",
		"Syme":                            "Syme",
		"Syr.":                            "Syr.",
		"Syr.-Phoen.":                     "Syr.-Phoen.",
		"Syria":                           "Syria",
		"Syros":                           "Syros",
		"Söğütalan":                      "Söğütalan",
		"Söveköy":                         "Söveköy",
		"Şahinli":                        "Şahinli",
		"Şekerçeşme Quelle":            "Şekerçeşme Quelle",
		"Tabanlar":                        "Tabanlar",
		"Tafak":                           "Tafak",
		"Tahtalı Köy":                     "Tahtalı Köy",
		"Tanis (San)":                     "Tanis (San)",
		"Tarhalla":                        "Tarhalla",
		"Taşköy":                         "Taşköy",
		"Tauromenion":                     "Tauromenion",
		"Tavolia":                         "Tavolia",
		"Tegea":                           "Tegea",
		"Tekeli-Karşi Mahalle":           "Tekeli-Karşi Mahalle",
		"Tekke":                           "Tekke",
		"Tekkedere":                       "Tekkedere",
		"Telos":                           "Telos",
		"Tempelruine am alten Bett des G": "Tempelruine am alten Bett des G",
		"Tenedos":                         "Tenedos",
		"Tenos":                           "Tenos",
		"Tepecik Çiftliği":              "Tepecik Çiftliği",
		"Terenouthis (Kôm Abu Bellou)":    "Terenouthis (Kôm Abu Bellou)",
		"Termessos (Güllük)":              "Termessos (Güllük)",
		"Territorium Incertum":            "Territorium Incertum",
		"Tevfikiye_Hisarlık":              "Tevfikiye_Hisarlık",
		"Thasos":                          "Thasos",
		"Thebai":                          "Thebai",
		"Thera":                           "Thera",
		"Therasia":                        "Therasia",
		"Thess.":                          "Thess.",
		"Thessalia":                       "Thessalia",
		"Thessaliotis":                    "Thessaliotis",
		"Thessalonike; Abydos":            "Thessalonike; Abydos",
		"Thessaly":                        "Thessaly",
		"Thr.":                            "Thr.",
		"Thrace":                          "Thrace",
		"Thracia":                         "Thracia",
		"Thrak. Chersones":                "Thrak. Chersones",
		"Thrakia":                         "Thrakia",
		"Thrakien":                        "Thrakien",
		"Thymbra (Akça Köy)":             "Thymbra (Akça Köy)",
		"Thymbraion (Hanay-Tepe)":         "Thymbraion (Hanay-Tepe)",
		"Tithora":                         "Tithora",
		"Tolbuhin":                        "Tolbuhin",
		"Tomis":                           "Tomis",
		"Tophısar":                        "Tophısar",
		"Transpadana":                     "Transpadana",
		"Tristomo":                        "Tristomo",
		"Troad":                           "Troad",
		"Troas":                           "Troas",
		"Troiz.":                          "Troiz.",
		"Troizenis":                       "Troizenis",
		"Trozenis":                        "Trozenis",
		"Trz.":                            "Trz.",
		"Trümmerfeld Kedik Weren Assar":   "Trümmerfeld Kedik Weren Assar",
		"Tschai Köy":                      "Tschai Köy",
		"Tuzla":                           "Tuzla",
		"Uluabat":                         "Uluabat",
		"Umbria":                          "Umbria",
		"Umgebung Devecikonağı":          "Umgebung Devecikonağı",
		"Umgebung von Apollonia ad Rhynd": "Umgebung von Apollonia ad Rhynd",
		"Umgebung von Çanpazar":          "Umgebung von Çanpazar",
		"Umgebung von Demirciler":         "Umgebung von Demirciler",
		"Umgebung von Edremit u. Ören":    "Umgebung von Edremit u. Ören",
		"Umgebung von Hadrianoi pros Oly": "Umgebung von Hadrianoi pros Oly",
		"Umgebung von Harmancik":          "Umgebung von Harmancik",
		"Umgebung von Haydar":             "Umgebung von Haydar",
		"Umgebung von Karacabey":          "Umgebung von Karacabey",
		"Umgebung von Kyzikos oder Band#": "Umgebung von Kyzikos oder Band#",
		"Umgebung von Lapseki (Maltarlas": "Umgebung von Lapseki (Maltarlas",
		"Umgebung von Miletupolis() (Me":  "Umgebung von Miletupolis() (Me",
		"Umgebung von Pergamon":           "Umgebung von Pergamon",
		"Umgebung von Sarıdüzü":           "Umgebung von Sarıdüzü",
		"Umgebung von Selimağa":          "Umgebung von Selimağa",
		"Umgebung von Taşköy":            "Umgebung von Taşköy",
		"Unk.":                            "Unk.",
		"Unk.Prov.":                       "Unk.Prov.",
		"Unterwasserfund":                 "Unterwasserfund",
		"Uzunöz":                          "Uzunöz",
		"Venetia":                         "Venetia",
		"W. Crete":                        "W. Crete",
		"West Lokris":                     "West Lokris",
		"Yaylacık":                        "Yaylacık",
		"Yeni Kuyu":                       "Yeni Kuyu",
		"Yenice":                          "Yenice",
		"Yenice bei Devecikonağı":        "Yenice bei Devecikonağı",
		"Yenidanişment":                  "Yenidanişment",
		"Yenije Kurshunlu":                "Yenije Kurshunlu",
		"Yeniköy":                         "Yeniköy",
		"Yeniköy nordöstl. von Kocapϟ":    "Yeniköy nordöstl. von Kocapϟ",
		"Yenişehir":                      "Yenişehir",
		"Yenizıraatlı":                    "Yenizıraatlı",
		"Yeşilçomlu":                    "Yeşilçomlu",
		"Yukarıyapıcı":                    "Yukarıyapıcı",
		"Yumurtaada Ad.":                  "Yumurtaada Ad.",
		"Yıldız":                          "Yıldız",
		"Zeleia (Sarıköy)":                "Zeleia (Sarıköy)",
		"Zeus Olbios bei Buğdaylı":       "Zeus Olbios bei Buğdaylı",
		"Zeus Olbios bei Yenice ／ bei":    "Zeus Olbios bei Yenice ／ bei",
		"Zeus Olympios (Ilıca)":           "Zeus Olympios (Ilıca)",
		"Zeytinbağı bei Mudanya (":       "Zeytinbağı bei Mudanya (",
		"Zeytindağ":                      "Zeytindağ",
		"Zeytinli Ada":                    "Zeytinli Ada",
		"am Bache Kalafatlı Azmağ":       "am Bache Kalafatlı Azmağ",
		"am Südhang des Çığr#":          "am Südhang des Çığr#",
		"an den Dardanellen":              "an den Dardanellen",
		"an der Bandırma-Erdek-Stras":     "an der Bandırma-Erdek-Stras",
		"an der Strasse Bursa_Lopadion":   "an der Strasse Bursa_Lopadion",
		"auf dem Hügel Dede":              "auf dem Hügel Dede",
		"bei Abydos":                      "bei Abydos",
		"bei Akçalar":                    "bei Akçalar",
		"bei Akşakal":                    "bei Akşakal",
		"bei Aslıhan":                     "bei Aslıhan",
		"bei Aşağı Kır𐅽":                "bei Aşağı Kır𐅽",
		"bei Bandırma":                    "bei Bandırma",
		"bei Bergaz":                      "bei Bergaz",
		"bei Cıplak":                      "bei Cıplak",
		"bei Çağış":                    "bei Çağış",
		"bei Çandarlı":                   "bei Çandarlı",
		"bei Çatalağıl":                 "bei Çatalağıl",
		"bei Çiplak":                     "bei Çiplak",
		"bei Edincik":                     "bei Edincik",
		"bei Elaia":                       "bei Elaia",
		"bei Etili":                       "bei Etili",
		"bei Geyikli":                     "bei Geyikli",
		"bei Halileli":                    "bei Halileli",
		"bei Hissaralan":                  "bei Hissaralan",
		"bei Ilıca":                       "bei Ilıca",
		"bei Kane (Killik Burun)":         "bei Kane (Killik Burun)",
		"bei Kazıkbağları":               "bei Kazıkbağları",
		"bei Kepsut":                      "bei Kepsut",
		"bei Kestambul Kaplıcası":         "bei Kestambul Kaplıcası",
		"bei Koğancı":                    "bei Koğancı",
		"bei Kurşunlu":                   "bei Kurşunlu",
		"bei Kuzköy":                      "bei Kuzköy",
		"bei Malea (Dikili)":              "bei Malea (Dikili)",
		"bei Miletupolis() (Melde)":       "bei Miletupolis() (Melde)",
		"bei Nusrat":                      "bei Nusrat",
		"bei Omerköy":                     "bei Omerköy",
		"bei Parion (Kemer)":              "bei Parion (Kemer)",
		"bei Reşadiye Iskele":            "bei Reşadiye Iskele",
		"bei Serceler":                    "bei Serceler",
		"bei Tekkedere":                   "bei Tekkedere",
		"beim Emir Çesme":                "beim Emir Çesme",
		"beim römischen Aquädukt":         "beim römischen Aquädukt",
		"fanum Apollinis":                 "fanum Apollinis",
		"im Kara Dağ":                    "im Kara Dağ",
		"in／bei Pınarbaşı":               "in／bei Pınarbaşı",
		"kos":                             "kos",
		"n. Black Sea":                    "n. Black Sea",
		"nahe Akçaköy":                   "Akçaköy",
		"nahe Aliova":                     "Aliova",
		"nahe Ayşebacı":                  "Ayşebacı",
		"nahe Balıklıçeşme":             "Balıklıçeşme",
		"nahe Bükköy":                     "Bükköy",
		"nahe Büyükbalıklı":               "Büyükbalıklı",
		"nahe Çandarlı":                  "Çandarlı",
		"nahe Çardak":                    "Çardak",
		"nahe Debleki":                    "Debleki",
		"nahe Ilion":                      "Ilion",
		"nahe Ilion (Hısarlık-Te":         "Ilion",
		"nahe Işıklar":                   "Işıklar",
		"nahe Koşuboğazıköy":            "Koşuboğazıköy",
		"nahe Odaköy":                     "Odaköy",
		"nahe Parion (Kemer)":             "Parion (Kemer)",
		"nahe Serceler":                   "Serceler",
		"nahe Serceler ／ Orhaneli":        "Serceler ／ Orhaneli",
		"nahe Taşköy":                    "Taşköy",
		"nahe Tevfikiye_Hisarlık":         "Tevfikiye_Hisarlık",
		"nahe der Mühle bei Konakpı":      "der Mühle bei Konakpı",
		"nordwestl. von Daskyleion (Ergi": "nordwestl. von Daskyleion (Ergi",
		"nächst dem Brunnen Gürgencik":    "nächst dem Brunnen Gürgencik",
		"nächste Umgebung von Kıran":      "nächste Umgebung von Kıran",
		"nördl. Halileli":                 "nördl. Halileli",
		"nördl. von Elaia":                "nördl. von Elaia",
		"nördl. von Reşadiye Iskele":     "nördl. von Reşadiye Iskele",
		"nördlich von Halileli":           "nördlich von Halileli",
		"nördlich von Türkmenli":          "nördlich von Türkmenli",
		"oberhalb Daskyleion (Ergili)":    "oberhalb Daskyleion (Ergili)",
		"oberhalb Ilhan am Berg Yatakbas": "oberhalb Ilhan am Berg Yatakbas",
		"place":                           "place",
		"prov.":                           "prov.",
		"region":                          "region",
		"südl. der röm. Bäder von Ili":    "südl. der röm. Bäder von Ili",
		"südl. von Gönen":                 "südl. von Gönen",
		"südl. von Kurtlar":               "südl. von Kurtlar",
		"südl. von Reşadiye Iskele":      "südl. von Reşadiye Iskele",
		"unterhalb Sirinçavuş":          "unterhalb Sirinçavuş",
		"unterhalb Zırafta":               "unterhalb Zırafta",
		"vermutlich Pınarbaşı":           "vermutlich Pınarbaşı",
		"westl. von Gönen":                "westl. von Gönen",
		"westl. von Pınarbaşı":           "westl. von Pınarbaşı",
		"zw. Aksakal u. Ergili":           "zw. Aksakal u. Ergili",
		"zw. Bandırma u. Aksakal":         "zw. Bandırma u. Aksakal",
		"zw. Bandırma u. Manyas":          "zw. Bandırma u. Manyas",
		"zw. Bergama u. Soma":             "zw. Bergama u. Soma",
		"zw. Bergama u. dem Kaikos":       "zw. Bergama u. dem Kaikos",
		"zw. Ciğrı-Dağ und Ezi":         "zw. Ciğrı-Dağ und Ezi",
		"zw. Çakırca u. Sevketiye":       "zw. Çakırca u. Sevketiye",
		"zw. Çanakkale u. Scharischeh":   "zw. Çanakkale u. Scharischeh",
		"zw. Çıplak und Pınar":           "zw. Çıplak und Pınar",
		"zw. Dikeli und Bergama":          "zw. Dikeli und Bergama",
		"zw. Eskidsche und Gümüldschin":   "zw. Eskidsche und Gümüldschin",
		"zw. Ezine und Marmat":            "zw. Ezine und Marmat",
		"zw. Ezine und Sarımsakl𐅽":        "zw. Ezine und Sarımsakl𐅽",
		"zw. Gryneion und Çandarl𐅽":      "zw. Gryneion und Çandarl𐅽",
		"zw. Karacabey u. Mustafakemalpa": "zw. Karacabey u. Mustafakemalpa",
		"zw. Kyzikos u. Edincik":          "zw. Kyzikos u. Edincik",
		"zw. Maltepe und Turm am Meer":    "zw. Maltepe und Turm am Meer",
		"zw. Mussatscha u. Pascha-Tsifli": "zw. Mussatscha u. Pascha-Tsifli",
		"zw. dem Hafen des Elaia und Zey": "zw. dem Hafen des Elaia und Zey",
		"Äg. Inseln":                      "Aegean Islands",
		"Äg.Inseln":                       "Aegean Islands",
		"Äg.Insëln":                       "Aegean Islands",
		"Ägypt.":                          "Egypt",
		"Ägypten":                         "Egypt",
		"Ömeli":                           "Ömeli",
		"Ömerköy":                         "Ömerköy",
		"östl. von Durabeyler":            "östl. von Durabeyler",
		"östl. von Pergamon":              "östl. von Pergamon",
	}
)

func remapprov(p string) string {
	// rewriting ok because the author + work title will display as:
	// `Cyprus · La chapelle d'Achoris à Karnak, #68: ICS 449 (Aegyptos, Karnak) [3 lines - 6 words]`
	// but the provenance will be set to `Egypt, Karnak` AND the provenance list in HGS will store this as just `Egypt`

	p = strings.ReplaceAll(p, "?", "")
	psegs := strings.Split(p, ",")
	for i, s := range psegs {
		pv, ok := provremapper[s]
		if !ok {
			psegs[i] = s
		} else {
			psegs[i] = pv
		}
	}
	return strings.Join(psegs, ",")
}
