package lexica

var (
	LatinAuthors = map[string]string{
		"Amm.":         "Ammianus",
		"Anthol. Lat.": "Latin Anthology",
		"App.":         "Apuleius",
		"Auct. Her.":   "Rhetorica ad Herennium",
		"Caes.":        "Caesar",
		"Cat.":         "Catullus",
		"Cassiod.":     "Cassiodorus",
		"Cels.":        "Celsus",
		"Charis.":      "Charisius",
		"Cic.":         "Cicero",
		"Col.":         "Columella",
		"Curt.":        "Quintus Curtius Rufus",
		"Dig.":         "Digest of Justinian",
		"Enn.":         "Ennius",
		"Eutr.":        "Eutropius",
		"Fest.":        "Festus",
		"Flor.":        "Florus",
		"Front.":       "Frontinus",
		"Gell.":        "Gellius",
		"Hirt.":        "Hirtius",
		"Hor.":         "Horace",
		"Hyg.":         "Hyginus",
		"Isid.":        "Isidore",
		"Just.":        "Justinian",
		"Juv.":         "Juvenal",
		"Lact.":        "Lactantius",
		"Liv.":         "Livy",
		"Luc.":         "Lucan",
		"Lucr.":        "Lucretius",
		"Macr.":        "Macrobius",
		"Mart.":        "Martial",
		"Nep.":         "Nepos",
		"Non.":         "Nonius",
		"Ov.":          "Ovid",
		"Pall.":        "Palladius",
		"Pers.":        "Persius",
		"Petr.":        "Petronius",
		"Phaedr.":      "Phaedrus",
		"Plaut.":       "Plautus",
		"Plin.":        "Pliny",
		"Prop.":        "Propertius",
		"Quint.":       "Quintilian",
		"Sall.":        "Sallust",
		"Sen.":         "Seneca",
		"Sil.":         "Silius Italicus",
		"Stat.":        "Statius",
		"Suet.":        "Suetonius",
		"Tac.":         "Tacitus",
		"Ter.":         "Terence",
		"Tert.":        "Tertullian",
		"Tib.":         "Tibullus",
		"Val. Fl.":     "Valerius Flaccus",
		"Val. Max.":    "Valerius Maxiumus",
		"Varr.":        "Varro",
		"Vell.":        "Velleius",
		"Verg.":        "Vergil",
		"Vitr.":        "Vitruvius",
		"Vulg.":        "Latin Vulgate Bible",
	}
)
